"""
Segment Engine
==============
Translates JSON segment rule trees → SQLAlchemy WHERE clauses → runs against DB.

Supported rule fields
  customer:  name, email, city, tags, total_spend, order_count, last_order_date
  order:     any condition requiring JOIN with orders table (e.g. spent_in_last_n_days)

Supported operators
  eq, neq, gt, gte, lt, lte, contains, not_contains, in, not_in,
  is_null, is_not_null, days_ago (convenience for date arithmetic)

Rule schema (generated by Gemini AI)
-------------------------------------
{
  "operator": "AND",          # top-level combinator: AND | OR
  "conditions": [
    { "field": "total_spend",     "op": "gte",      "value": 5000 },
    { "field": "last_order_date", "op": "days_ago", "value": 90   },
    { "field": "tags",            "op": "contains", "value": "vip"},
    { "field": "city",            "op": "in",       "value": ["Mumbai","Delhi"] }
  ]
}
"""

from __future__ import annotations

import logging
from typing import Any

from sqlalchemy import and_, or_, select, func, text, String as sa_String
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Customer

log = logging.getLogger(__name__)


# ── Public API ───────────────────────────────────────────────────────────────

async def evaluate_segment(
    rules: dict,
    db: AsyncSession,
    *,
    preview_limit: int = 5,
) -> dict:
    """
    Run segment rules against the DB.

    Returns:
        {
            "count": int,
            "sample_customers": [Customer, ...],
            "sql_preview": str,
        }
    """
    where_clause = _build_where(rules)
    base_q = select(Customer).where(where_clause)

    # count
    count_q = select(func.count()).select_from(base_q.subquery())
    count = (await db.execute(count_q)).scalar_one()

    # sample
    sample_q = base_q.limit(preview_limit)
    result = await db.execute(sample_q)
    sample = result.scalars().all()

    # human-readable SQL for display
    sql_preview = _rules_to_sql_preview(rules)

    return {
        "count": count,
        "sample_customers": sample,
        "sql_preview": sql_preview,
    }


async def get_segment_customer_ids(rules: dict, db: AsyncSession) -> list[str]:
    """Return ALL customer IDs matching the segment (for dispatch)."""
    where_clause = _build_where(rules)
    q = select(Customer.id).where(where_clause)
    result = await db.execute(q)
    return [str(row) for row in result.scalars().all()]


# ── Internal: rule compiler ──────────────────────────────────────────────────

_FIELD_MAP = {
    "name":            Customer.name,
    "email":           Customer.email,
    "phone":           Customer.phone,
    "city":            Customer.city,
    "total_spend":     Customer.total_spend,
    "order_count":     Customer.order_count,
    "last_order_date": Customer.last_order_date,
    "tags":            Customer.tags,
}


def _build_where(rules: dict):
    """Recursively build a SQLAlchemy boolean expression from a rule tree."""
    operator = rules.get("operator", "AND").upper()
    conditions = rules.get("conditions", [])

    clauses = [_compile_condition(c) for c in conditions]

    if not clauses:
        # No conditions → match everyone
        return text("TRUE")

    if operator == "AND":
        return and_(*clauses)
    elif operator == "OR":
        return or_(*clauses)
    else:
        raise ValueError(f"Unknown operator: {operator}")


def _compile_condition(cond: dict):
    field_name: str = cond["field"]
    op: str = cond["op"]
    value: Any = cond.get("value")

    # Special handling: days_ago → compare last_order_date
    if op == "days_ago":
        return text(
            f"last_order_date < NOW() - INTERVAL '{int(value)} days' "
            f"OR last_order_date IS NULL"
        )

    col = _FIELD_MAP.get(field_name)
    if col is None:
        raise ValueError(f"Unknown segment field: {field_name!r}")

    match op:
        case "eq":          return col == value
        case "neq":         return col != value
        case "gt":          return col > value
        case "gte":         return col >= value
        case "lt":          return col < value
        case "lte":         return col <= value
        case "contains":
            if field_name == "tags":
                # :val_N = ANY(tags) — bindparam gives correct parameterized SQL
                from sqlalchemy import bindparam
                pname = f"tv{abs(hash(str(value))) % 999999}"
                return text(f":{pname} = ANY(tags)").bindparams(**{pname: str(value)})
            return col.ilike(f"%{value}%")
        case "not_contains":
            if field_name == "tags":
                from sqlalchemy import bindparam
                pname = f"ntv{abs(hash(str(value))) % 999999}"
                return text(f"NOT (:{pname} = ANY(tags))").bindparams(**{pname: str(value)})
            return ~col.ilike(f"%{value}%")
        case "in":
            return col.in_(value if isinstance(value, list) else [value])
        case "not_in":
            return col.not_in(value if isinstance(value, list) else [value])
        case "is_null":     return col.is_(None)
        case "is_not_null": return col.is_not(None)
        case _:
            raise ValueError(f"Unknown operator: {op!r}")


def _rules_to_sql_preview(rules: dict) -> str:
    """Generate a human-readable SQL WHERE string (for UI display only)."""
    operator = rules.get("operator", "AND").upper()
    conditions = rules.get("conditions", [])
    parts = []
    for c in conditions:
        field = c["field"]
        op = c["op"]
        val = c.get("value", "")
        if op == "days_ago":
            parts.append(f"last_order_date < NOW() - INTERVAL '{val} days'")
        elif op == "contains" and field == "tags":
            parts.append(f"'{val}' = ANY(tags)")
        elif op in ("gt", "gte", "lt", "lte", "eq", "neq"):
            sym = {"gt": ">", "gte": ">=", "lt": "<", "lte": "<=", "eq": "=", "neq": "!="}.get(op, op)
            parts.append(f"{field} {sym} {val!r}")
        elif op == "in":
            parts.append(f"{field} IN {tuple(val)}")
        else:
            parts.append(f"{field} {op} {val!r}")
    joiner = f" {operator} "
    return "WHERE " + joiner.join(parts) if parts else "WHERE TRUE"
